theme: charlolamode

menu:
    main:
        - name:
          url: /
        #   weight: 30
        # - name: Articles
        #   url: /articles/
        #   weight: 20
        # - name: Projects
        #   url: /projects/
        #   weight: 15
        # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs

params:
    author: Marco de Freitas
    defaultTheme: auto
    disableThemeToggle: true
    # ShowShareButtons: true
    # ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: Marco de Freitas
        description: |
          Remote contractor from Tavira, Portugal.
          
          I work mostly with .NET and JavaScript using agile software development enabling teams to be more human and less machine like.
          
          Feel free to reach me out if you want to talk about any idea, projects, mentoring, mock interviews or just having a chat.
        imageUrl: "/images/profile.png"
        imageTitle: me, myself and I
        buttons:
        #     - name: Don't click me
        #       url: https://www.youtube.com/watch?v=dQw4w9WgXcQ

    socialIcons:
        - name: buymeacoffee
          url: "https://ko-fi.com/marcodefreitas"
        - name: github
          url: "https://github.com/marcolinopt"
        - name: linkedin
          url: "https://www.linkedin.com/in/marcolinopt/"
        - name: email
          url: mailto:me@marcodefreitas.com
        - name: twitter
          url: "https://www.twitter.com/marcolinopt83"
        - name: facebook
          url: "https://www.facebook.com/soulnino"

    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"
